<a href="https://colab.research.google.com/github/Jennifer-Kafui/climate-modeling/blob/main/Climate_Action_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 3 , Making computing mistakes

In [1]:
#importing package(s) and create aliases

import numpy as np
#numpy is a core package for numerical arrays and linear algebra

from numpy import array
#array helps to build numpy arrays from python

from numpy.linalg import inv as inv
# to help in linear algebra calculations like inverse , transpose

Creating Arrays and Performing Math on them

In [2]:
# This is a normal list and not suited for our linear algebra calulations

a1 = [5,8, 13]
a1

[5, 8, 13]

In [3]:
#This is not a matrix

a2 = array([5, 8, 13])
a2

array([ 5,  8, 13])

In [4]:
a = array([[5, 8, 13]])
a

array([[ 5,  8, 13]])

Transpose

In [5]:
# .T on a Python list it won't work, works on only 2D array
# b1 = a1.T
#b1

In [6]:
#.T on a 1D array returns the same array (no actual transpose happens)
b2 = a2.T
b2

array([ 5,  8, 13])

In [7]:
# The is the right transpose
b = a.T
b

array([[ 5],
       [ 8],
       [13]])

Matrix Operations

In [8]:
# Multiplying a list by 2 repeats it
c1 = a1 * 2
c1

[5, 8, 13, 5, 8, 13]

In [9]:
# Multiplies the array by 2
c2 = a2 * 2
c2

array([10, 16, 26])

In [10]:
# Also multiplies the array by 2
c = a * 2
c

array([[10, 16, 26]])

In [11]:
# Also multiplies the array by 11
#x = array ([9,8,7]) * array(11)
x = array([9, 8, 7]) * 11
x

array([99, 88, 77])

In [12]:
# Python uses ** for exponentiation
# x = b ^ 3
d = b ** 3
d


array([[ 125],
       [ 512],
       [2197]])

In [13]:
p1 = a * b
p1

array([[ 25,  40,  65],
       [ 40,  64, 104],
       [ 65, 104, 169]])

In [14]:
p2 = a * b.T
p2

array([[ 25,  64, 169]])

In [15]:
p3 = a.T * b
p3

array([[ 25],
       [ 64],
       [169]])

In [16]:
p4 = a @ b
p4

array([[258]])

In [17]:
# Dimension mismatch
#p5 = a @ b.T
#p5

In [18]:
# Dimension mismatch
#p6 = a.T @ b
#p6

In [19]:
p7 = a.T @ b.T
p7

array([[ 25,  40,  65],
       [ 40,  64, 104],
       [ 65, 104, 169]])

In [20]:
p8 = a2 @ b2
p8

np.int64(258)

In [21]:
p9 = a2 @ b2.T
p9

np.int64(258)

In [22]:
q1 = a / b.T
q1

array([[1., 1., 1.]])

In [23]:
q1 = a.T / b
q1

array([[1.],
       [1.],
       [1.]])

In [24]:
q1 = a / b
q1

array([[1.        , 1.6       , 2.6       ],
       [0.625     , 1.        , 1.625     ],
       [0.38461538, 0.61538462, 1.        ]])

In [25]:
# There is no "\" in Python
# q2 = a \ b
# q2

Building Matrices

In [26]:
A1 = [b, b + 21, b ** 2]
A1

[array([[ 5],
        [ 8],
        [13]]),
 array([[26],
        [29],
        [34]]),
 array([[ 25],
        [ 64],
        [169]])]

In [27]:
# A2 is invalid syntax (array takes one argument, not three).
# A2 = array(b, b + 21, b ** 2)
# A2

In [28]:
A = np.vstack([a, a + 21, a ** 2])
A

array([[  5,   8,  13],
       [ 26,  29,  34],
       [ 25,  64, 169]])

In [29]:
x = inv(A) @ b
x

array([[-3.21428571],
       [ 4.51428571],
       [-1.15714286]])

In [30]:
z = A @ x - b
z

array([[-1.77635684e-15],
       [-1.33226763e-14],
       [ 3.55271368e-15]])

In [31]:
AtA = A.T @ A
AtA

array([[ 1326,  2394,  5174],
       [ 2394,  5001, 11906],
       [ 5174, 11906, 29886]])

Horizontal and Vertical Stacking

In [32]:
B = np.hstack([b, b ** 2])
B

array([[  5,  25],
       [  8,  64],
       [ 13, 169]])

In [33]:
C = np.vstack([c + 21, c ** 2])
C

array([[ 31,  37,  47],
       [100, 256, 676]])

In [34]:
D = array([[1, 2], [3, 4]])
D

array([[1, 2],
       [3, 4]])

In [35]:
# np.hstack([A, B]), (3x3), np.hstack([C, D]), (2x3) = Result (5x5)

S = np.vstack([ np.hstack([A, B]), np.hstack([C, D])])
S

array([[  5,   8,  13,   5,  25],
       [ 26,  29,  34,   8,  64],
       [ 25,  64, 169,  13, 169],
       [ 31,  37,  47,   1,   2],
       [100, 256, 676,   3,   4]])

Indexing and Slicing

In [36]:
# Slicing only works in the the brackets for arrays
# u = [0:10]
# u

In [37]:
u = np.linspace(1, 10, 10)
u

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
# u[10] is out of range
# v = u[10]
# v

In [39]:
# First number
v = u[0]
v

np.float64(1.0)

In [40]:
# Last number
v = u[-1]
v

np.float64(10.0)

In [41]:
# This indicates the numbers at position 2,3,4
v = u[2:5]
v

array([3., 4., 5.])

In [42]:
# This indicates numbers at position 2,3,4 and 5
v = u[2:5+1]
v


array([3., 4., 5., 6.])

In [43]:
# This means row 2, column 0
v = A[2,0]
v

np.int64(25)

In [44]:
# This also means row 3, column 0
v = A[2][0]
v

np.int64(25)

In [45]:
# The entire row 1
v = A[1, :]
v

array([26, 29, 34])

In [46]:
# This is for row 1 and 2, and all the columns
v = A[1:3, :]
v

array([[ 26,  29,  34],
       [ 25,  64, 169]])

In [47]:
# This is for row 1 and 2, columns 1 and 2
v = A[1:3, 1:3]
v

array([[ 29,  34],
       [ 64, 169]])

In [48]:
# This means start at the 6th index, and end at the second to last , increase by 2
v = u[6:-2:2]
v

array([7.])

In [49]:
# Picks up the elements at positions 6, 4 and 2
v = u[[6,4,2]]
v

array([7., 5., 3.])

Vector Mistakes

In [55]:
y = np.array([1,2,3]) * np.array([4,5,6])
y

array([ 4, 10, 18])

In [56]:
#To get a scalar result use
y1 = np .array([1,2,3]) @ np.array([4,5,6])
y1

np.int64(32)

In [58]:
#Using a float as an index
z = np.array([1, 2, 3, 4])
#z1 = z[2.0]
z1 = z[2]
# or
z1 = z[int(2.0)]
z1

np.int64(3)

In [64]:
# Mixing list sizes when making a matrix
#E = np.array([[1, 2], [3, 4, 5]])

E = np.array([[1, 2], [3, 4]])
E

array([[1, 2],
       [3, 4]])

In [71]:
# Summing entire matrix when you wanted rows or columns sums

F = np.array([[1, 2], [3, 4]])
F1 = np.sum(F)
F1


np.int64(10)

In [76]:
# Specify axis
row_sums = np.sum(F, axis=1)
col_sums = np.sum(F, axis=0)
row_sums
col_sums

array([4, 6])