<a href="https://colab.research.google.com/github/Jennifer-Kafui/climate-modeling/blob/main/Climate_Action_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 3 , Making computing mistakes

In [ ]:
#importing package(s) and create aliases

import numpy as np
#numpy is a core package for numerical arrays and linear algebra

from numpy import array
#array helps to build numpy arrays from python

from numpy.linalg import inv as inv
# to help in linear algebra calculations like inverse , transpose

Creating Arrays and Performing Math on them

In [ ]:
# This is a normal list and not suited for our linear algebra calulations

a1 = [5,8, 13]
a1

[5, 8, 13]

In [ ]:
#This is not a matrix

a2 = array([5, 8, 13])
a2

array([ 5,  8, 13])

In [ ]:
a = array([[5, 8, 13]])
a

array([[ 5,  8, 13]])

Transpose

In [ ]:
# .T on a Python list it won't work, works on only 2D array
# b1 = a1.T
b1

In [ ]:
#.T on a 1D array returns the same array (no actual transpose happens)
b2 = a2.T
b2

array([ 5,  8, 13])

In [ ]:
# The is the right transpose
b = a.T
b

array([[ 5],
       [ 8],
       [13]])

Matrix Operations

In [ ]:
# Multiplying a list by 2 repeats it
c1 = a1 * 2
c1

[5, 8, 13, 5, 8, 13]

In [ ]:
# Multiplies the array by 2
c2 = a2 * 2
c2

array([10, 16, 26])

In [ ]:
# Also multiplies the array by 2
c = a * 2
c

array([[10, 16, 26]])

In [ ]:
# Also multiplies the array by 11
#x = array ([9,8,7]) * array(11)
x = array([9, 8, 7]) * 11
x

array([99, 88, 77])

In [ ]:
# Python uses ** for exponentiation
# x = b ^ 3
d = b ** 3
d


array([[ 125],
       [ 512],
       [2197]])

In [ ]:
p1 = a * b
p1

array([[ 25,  40,  65],
       [ 40,  64, 104],
       [ 65, 104, 169]])

In [ ]:
p2 = a * b.T
p2

array([[ 25,  64, 169]])

In [ ]:
p3 = a.T * b
p3

array([[ 25],
       [ 64],
       [169]])

In [ ]:
p4 = a @ b
p4

array([[258]])

In [ ]:
# Dimension mismatch
#p5 = a @ b.T
#p5

In [ ]:
# Dimension mismatch
#p6 = a.T @ b
#p6

In [ ]:
p7 = a.T @ b.T
p7

array([[ 25,  40,  65],
       [ 40,  64, 104],
       [ 65, 104, 169]])

In [ ]:
p8 = a2 @ b2
p8

np.int64(258)

In [ ]:
p9 = a2 @ b2.T
p9

np.int64(258)

In [ ]:
q1 = a / b.T
q1

array([[1., 1., 1.]])

In [ ]:
q1 = a.T / b
q1

array([[1.],
       [1.],
       [1.]])

In [ ]:
q1 = a / b
q1

array([[1.        , 1.6       , 2.6       ],
       [0.625     , 1.        , 1.625     ],
       [0.38461538, 0.61538462, 1.        ]])

In [ ]:
# There is no "\" in Python
# q2 = a \ b
# q2

Building Matrices

In [ ]:
A1 = [b, b + 21, b ** 2]
A1

[array([[ 5],
        [ 8],
        [13]]),
 array([[26],
        [29],
        [34]]),
 array([[ 25],
        [ 64],
        [169]])]

In [ ]:
# A2 is invalid syntax (array takes one argument, not three)
# A2 = array(b, b + 21, b ** 2)
# A2

In [ ]:
A = np.vstack([a, a + 21, a ** 2])
A

array([[  5,   8,  13],
       [ 26,  29,  34],
       [ 25,  64, 169]])

In [ ]:
x = inv(A) @ b
x

array([[-3.21428571],
       [ 4.51428571],
       [-1.15714286]])

In [ ]:
z = A @ x - b
z

array([[-1.77635684e-15],
       [-1.33226763e-14],
       [ 3.55271368e-15]])

In [ ]:
AtA = A.T @ A
AtA

array([[ 1326,  2394,  5174],
       [ 2394,  5001, 11906],
       [ 5174, 11906, 29886]])

Horizontal and Vertical Stacking

In [ ]:
B = np.hstack([b, b ** 2])
B

array([[  5,  25],
       [  8,  64],
       [ 13, 169]])

In [ ]:
C = np.vstack([c + 21, c ** 2])
C

array([[ 31,  37,  47],
       [100, 256, 676]])

In [ ]:
D = array([[1, 2], [3, 4]])
D

array([[1, 2],
       [3, 4]])

In [ ]:
# np.hstack([A, B]), (3x3), np.hstack([C, D]), (2x3) = Result (5x5)

S = np.vstack([ np.hstack([A, B]), np.hstack([C, D])])
S

array([[  5,   8,  13,   5,  25],
       [ 26,  29,  34,   8,  64],
       [ 25,  64, 169,  13, 169],
       [ 31,  37,  47,   1,   2],
       [100, 256, 676,   3,   4]])

Indexing and Slicing

In [ ]:
# Slicing only works in the the brackets for arrays
# u = [0:10]
# u

In [ ]:
u = np.linspace(1, 10, 10)
u

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# u[10] is out of range
# v = u[10]
# v

In [ ]:
# First number
v = u[0]
v

np.float64(1.0)

In [ ]:
# Last number
v = u[-1]
v

np.float64(10.0)

In [ ]:
# This indicates the numbers at position 2,3,4
v = u[2:5]
v

array([3., 4., 5.])

In [ ]:
# This indicates numbers at position 2,3,4 and 5
v = u[2:5+1]
v


array([3., 4., 5., 6.])

In [ ]:
# This means row 2, column 0
v = A[2,0]
v

np.int64(25)

In [ ]:
# This also means row 3, column 0
v = A[2][0]
v

np.int64(25)

In [ ]:
# The entire row 1
v = A[1, :]
v

array([26, 29, 34])

In [ ]:
# This is for row 1 and 2, and all the columns
v = A[1:3, :]
v

array([[ 26,  29,  34],
       [ 25,  64, 169]])

In [ ]:
# This is for row 1 and 2, columns 1 and 2
v = A[1:3, 1:3]
v

array([[ 29,  34],
       [ 64, 169]])

In [ ]:
# This means start at the 6th index, and end at the second to last , increase by 2
v = u[6:-2:2]
v

array([7.])

In [ ]:
# Picks up the elements at positions 6, 4 and 2
v = u[[6,4,2]]
v

array([7., 5., 3.])