<a href="https://colab.research.google.com/github/Jennifer-Kafui/climate-modeling/blob/main/rankA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

m = 2 #number of rows of A
n = 5 #number of coumns of A
A = np.random.randn(m,n) # an m by n matrix of random numbers
A

array([[ 1.21275823,  0.05657453,  1.43709769,  1.97546295,  0.19128172],
       [-3.76357844,  0.85255527,  0.21317351,  0.65820456, -1.67880253]])

In [2]:
AtA = A.T @ A
AtA

array([[15.63530517, -3.1400474 ,  0.94055681, -0.08144557,  6.55028347],
       [-3.1400474 ,  0.73005116,  0.26304532,  0.67291665, -1.42045027],
       [ 0.94055681,  0.26304532,  2.11069271,  2.97924501, -0.08298572],
       [-0.08144557,  0.67291665,  2.97924501,  4.3356871 , -0.72712554],
       [ 6.55028347, -1.42045027, -0.08298572, -0.72712554,  2.85496662]])

In [3]:
AAt = A @ A.T
AAt

array([[ 7.4782755 , -3.23059214],
       [-3.23059214, 18.18842726]])

In [4]:
sizeA = A.shape
sizeA

(2, 5)

In [5]:
rankA = np.linalg.matrix_rank (A)
rankA

np.int64(2)

In [6]:
sizeAtA = AtA.shape
sizeAtA

(5, 5)

In [7]:
rankAtA = np.linalg.matrix_rank (AtA)
rankAtA

np.int64(2)

In [8]:
sizeAAt = AAt.shape
sizeAAt

(2, 2)

In [9]:
rankAAt = np.linalg.matrix_rank (AAt)
rankAAt

np.int64(2)

In [10]:
print (" size (A ) = " , sizeA )
print (" rank (A ) = " , rankA )
print (" size ( AtA ) =" , sizeAtA )
print (" rank ( AtA ) =" , rankAtA )
print (" size ( AAt ) =" , sizeAAt )
print (" rank ( AAt ) =" , rankAAt )

 size (A ) =  (2, 5)
 rank (A ) =  2
 size ( AtA ) = (5, 5)
 rank ( AtA ) = 2
 size ( AAt ) = (2, 2)
 rank ( AAt ) = 2


When I try different matrix sizes, the rank is never bigger than the smaller of m or n, which makes sense because you can not get more independent rows or columns than what you actually have.

For m = 2, the rank of AAt,  AAt is 1 if the two rows in A are basically the same line, just multiples of each other.